server:
  port: 8111
spring:
  application:
    name: swcamp-user-service

  ## db config
  detasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306:menudb
    username: root
    password: mariadb

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    database: mysql

    properties:
      hibernate:
        '[format_sql]' : true
