server:
  port: 8000 # ?????? ????? 8000? ??

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    servcie-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:   # ??????? ??
        #
        - id: 1st-service-get
#          uri: http://localhost:51946/ # ?? ???? ??
          # ??? ? ???? ??? application name? ??(??? ??? ?????? ?? ??)
          uri: lb://1ST-SERVICE         # ?????

          # ?????? ??? ??? ?? ???? ??? (??? ???)
          predicates:
            - Path=/first-service/**

          # ?? ??? ? ???? ???? /fiirst-service ?? ???? ???? ???? ? ?? + ??
          filters:
            - RewritePath=/first-service/(?<segment>.*),/$\{segment}    # ???(?<segment>.*)?  $\{segment} ?????? ???
            # Spring Cloud native ? ????? ??? ?? ??, ?????? ??.
            - AddRequestHeader=first-request, first-request-header      # ???
            - AddResponseHeader=first-response, first-response-header   # ???

        - id: 2nd-service-get
#          uri: http://localhost:51725/
          uri: lb://2ND-SERVICE         # ?????
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*),/$\{segment}
