server:
  port: 8761

eureka:
  client:

    # eureka server? eureka server?? ???? ??? ??? x
    register-with-eureka: false

    # eureka server? ?? micro service?? ?????(30???) ???? ??? ??? ??.
    fetch-registry: false
